BEGIN TRANSACTION;

INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Manutenção de sistema', 764.43, 'Receita', '2026-10-01', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Venda de bicicleta', 741.01, 'Receita', '2026-10-01', 'Venda', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Tarifa bancária', 39.45, 'Despesa', '2026-10-01', 'Financeiro', '2027-10-01');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Condomínio', 576.00, 'Despesa', '2026-10-01', 'Conta Essencial', '2027-10-01');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('13º salário', 2570.13, 'Receita', '2026-10-02', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Material escolar', 65.00, 'Despesa', '2026-10-02', 'Educacao', '2027-06-09');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Barbearia/salão', 63.42, 'Despesa', '2026-10-02', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Restituição', 482.90, 'Receita', '2026-10-02', 'Outras Entradas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Certificação', 423.33, 'Despesa', '2026-10-03', 'Educacao', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Design de logo', 430.14, 'Receita', '2026-10-03', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Internet residencial', 115.93, 'Despesa', '2026-10-03', 'Conta Essencial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Software empresarial', 450.75, 'Despesa', '2026-10-03', 'Empresarial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Presente de aniversário', 106.39, 'Despesa', '2026-10-01', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Farmácia', 29.29, 'Despesa', '2026-10-02', 'Saúde', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Presente de aniversário', 208.54, 'Despesa', '2026-10-03', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Software empresarial', 342.89, 'Despesa', '2025-03-07', 'Empresarial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('IPTU', 423.09, 'Despesa', '2025-03-07', 'Fiscal', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Conta de água', 78.93, 'Despesa', '2025-03-17', 'Conta Essencial', '2026-05-11');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Taxa de licenciamento', 151.51, 'Despesa', '2025-03-22', 'Fiscal', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('13º salário', 1604.56, 'Receita', '2025-03-24', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Cashback', 32.33, 'Receita', '2025-03-24', 'Outras Entradas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Conserto doméstico', 118.80, 'Despesa', '2025-03-31', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Consulta médica', 410.73, 'Despesa', '2025-04-03', 'Saúde', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Venda de móveis', 154.66, 'Receita', '2025-04-06', 'Venda', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Taxa de licenciamento', 159.84, 'Despesa', '2025-04-07', 'Fiscal', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('DAS MEI', 71.66, 'Despesa', '2025-04-14', 'Fiscal', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Venda de console de videogame', 2018.92, 'Receita', '2025-04-16', 'Venda', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Seguro de vida', 60.45, 'Despesa', '2025-04-18', 'Seguro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Consultoria', 1756.48, 'Receita', '2025-04-19', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Dentista', 507.72, 'Despesa', '2025-04-19', 'Saúde', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Taxa de licenciamento', 147.96, 'Despesa', '2025-04-21', 'Fiscal', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Plano de saúde', 796.31, 'Despesa', '2025-04-26', 'Saúde', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Férias', 2633.79, 'Receita', '2025-04-27', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Transporte por aplicativo', 35.93, 'Despesa', '2025-04-30', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Viagem de fim de semana', 975.21, 'Despesa', '2025-05-05', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Internet residencial', 90.61, 'Despesa', '2025-05-06', 'Conta Essencial', '2026-12-27');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Gympass', 137.99, 'Despesa', '2025-05-06', 'Assinatura', '2026-08-29');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Doação', 191.57, 'Despesa', '2025-05-06', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Plano de saúde', 398.07, 'Despesa', '2025-05-09', 'Saúde', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Venda de console de videogame', 959.24, 'Receita', '2025-05-13', 'Venda', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Consultoria', 1930.36, 'Receita', '2025-05-15', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Disney+', 40.59, 'Despesa', '2025-05-19', 'Assinatura', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Gympass', 132.98, 'Despesa', '2025-05-20', 'Assinatura', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Barbearia/salão', 76.04, 'Despesa', '2025-05-22', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Supermercado', 331.19, 'Despesa', '2025-05-25', 'Conta Essencial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Exames laboratoriais', 111.48, 'Despesa', '2025-05-26', 'Saúde', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Seguro de vida', 71.94, 'Despesa', '2025-05-27', 'Seguro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Curso online', 408.06, 'Despesa', '2025-05-30', 'Educacao', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Pix recebido de amigo', 136.98, 'Receita', '2025-06-04', 'Outras Entradas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Gás de cozinha', 113.87, 'Despesa', '2025-06-17', 'Conta Essencial', '2025-12-14');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Seguro de vida', 59.72, 'Despesa', '2025-06-22', 'Seguro', '2025-10-20');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Netflix', 44.10, 'Despesa', '2025-06-23', 'Assinatura', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Contador', 450.07, 'Despesa', '2025-06-24', 'Empresarial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Presente em dinheiro', 322.74, 'Receita', '2025-06-24', 'Outras Entradas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Financiamento do carro', 759.55, 'Despesa', '2025-06-24', 'Financeiro', '2027-06-14');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Conserto doméstico', 451.07, 'Despesa', '2025-07-03', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Juros de cheque especial', 91.25, 'Despesa', '2025-07-13', 'Financeiro', '2027-03-05');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Aula particular', 124.42, 'Receita', '2025-07-19', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Salário mensal', 5396.48, 'Receita', '2025-07-23', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('13º salário', 1807.26, 'Receita', '2025-07-28', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Reembolso', 201.61, 'Receita', '2025-08-03', 'Outras Entradas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Juros de cheque especial', 28.28, 'Despesa', '2025-08-05', 'Financeiro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Salário mensal', 6363.36, 'Receita', '2025-08-05', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Presente em dinheiro', 198.49, 'Receita', '2025-08-13', 'Outras Entradas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Material de escritório', 52.75, 'Despesa', '2025-08-14', 'Empresarial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Design de logo', 870.74, 'Receita', '2025-09-05', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Conta de luz', 234.41, 'Despesa', '2025-09-06', 'Conta Essencial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Taxa de licenciamento', 139.84, 'Despesa', '2025-09-19', 'Fiscal', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Viagem de fim de semana', 1209.91, 'Despesa', '2025-09-19', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Amazon Prime', 15.71, 'Despesa', '2025-09-20', 'Assinatura', '2027-01-13');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Coworking', 279.25, 'Despesa', '2025-09-26', 'Empresarial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Parque/passeio', 107.34, 'Despesa', '2025-09-27', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('YouTube Premium', 26.23, 'Despesa', '2025-09-28', 'Assinatura', '2027-01-21');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Manutenção de sistema', 1407.46, 'Receita', '2025-10-03', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Presente em dinheiro', 302.72, 'Receita', '2025-10-10', 'Outras Entradas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Curso online', 39.81, 'Despesa', '2025-10-11', 'Educacao', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Seguro residencial', 74.26, 'Despesa', '2025-10-15', 'Seguro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Condomínio', 645.29, 'Despesa', '2025-10-16', 'Conta Essencial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Internet residencial', 100.35, 'Despesa', '2025-10-27', 'Conta Essencial', '2026-10-22');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Taxa de licenciamento', 158.29, 'Despesa', '2025-11-02', 'Fiscal', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Disney+', 40.60, 'Despesa', '2025-11-12', 'Assinatura', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Pet shop', 93.93, 'Despesa', '2025-11-13', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Design de logo', 583.24, 'Receita', '2025-11-14', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Projeto freelance de site', 3011.07, 'Receita', '2025-11-21', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Venda de roupas', 217.24, 'Receita', '2025-11-22', 'Venda', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Restituição', 360.08, 'Receita', '2025-11-22', 'Outras Entradas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('13º salário', 1791.28, 'Receita', '2025-12-01', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Seguro residencial', 116.07, 'Despesa', '2025-12-03', 'Seguro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Seguro residencial', 116.37, 'Despesa', '2025-12-11', 'Seguro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Gás de cozinha', 118.59, 'Despesa', '2025-12-11', 'Conta Essencial', '2027-06-04');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Venda de console de videogame', 1620.35, 'Receita', '2025-12-15', 'Venda', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Rendimento de poupança', 96.21, 'Receita', '2025-12-16', 'Outras Entradas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Cinema', 62.53, 'Despesa', '2025-12-17', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Combustível', 190.13, 'Despesa', '2025-12-19', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Curso de inglês', 230.38, 'Despesa', '2025-12-27', 'Educacao', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Conta de luz', 103.38, 'Despesa', '2025-12-28', 'Conta Essencial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Mensalidade da faculdade', 1243.86, 'Despesa', '2025-12-29', 'Educacao', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Academia', 75.44, 'Despesa', '2025-12-31', 'Saúde', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Design de logo', 472.33, 'Receita', '2025-12-31', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Show', 310.78, 'Despesa', '2025-12-31', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Conta de celular', 105.44, 'Despesa', '2025-12-31', 'Conta Essencial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Show', 203.00, 'Despesa', '2026-01-01', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Aluguel', 1627.54, 'Despesa', '2026-01-03', 'Conta Essencial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Barbearia/salão', 81.88, 'Despesa', '2026-01-04', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Consultoria', 445.73, 'Receita', '2026-01-10', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Gympass', 117.97, 'Despesa', '2026-01-12', 'Assinatura', '2027-04-07');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Venda de móveis', 230.00, 'Receita', '2026-01-17', 'Venda', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Venda de console de videogame', 1891.05, 'Receita', '2026-01-21', 'Venda', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Conserto doméstico', 318.62, 'Despesa', '2026-02-04', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Bônus de desempenho', 589.29, 'Receita', '2026-02-07', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Juros de cheque especial', 106.92, 'Despesa', '2026-02-12', 'Financeiro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Show', 259.33, 'Despesa', '2026-02-13', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('iCloud', 4.29, 'Despesa', '2026-02-13', 'Assinatura', '2028-01-04');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Show', 347.85, 'Despesa', '2026-02-14', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Manutenção de sistema', 922.56, 'Receita', '2026-02-16', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Bônus de desempenho', 576.02, 'Receita', '2026-02-18', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('13º salário', 1884.93, 'Receita', '2026-02-25', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Bar com amigos', 47.59, 'Despesa', '2026-02-25', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Dentista', 358.85, 'Despesa', '2026-03-02', 'Saúde', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Gympass', 140.91, 'Despesa', '2026-03-05', 'Assinatura', '2026-12-30');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Financiamento do carro', 791.44, 'Despesa', '2026-03-08', 'Financeiro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Seguro residencial', 110.70, 'Despesa', '2026-03-12', 'Seguro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Restaurante', 156.93, 'Despesa', '2026-03-13', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Consultoria', 2288.91, 'Receita', '2026-03-15', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Salário mensal', 5099.50, 'Receita', '2026-04-09', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Adiantamento salarial', 1183.48, 'Receita', '2026-04-12', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Parque/passeio', 44.88, 'Despesa', '2026-04-14', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Restaurante', 117.45, 'Despesa', '2026-04-16', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Rendimento de poupança', 104.30, 'Receita', '2026-04-16', 'Outras Entradas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Fatura do cartão de crédito', 871.57, 'Despesa', '2026-04-20', 'Financeiro', '2027-06-14');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Consultoria', 1546.19, 'Receita', '2026-04-30', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Projeto freelance de site', 674.19, 'Receita', '2026-05-03', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Seguro viagem', 211.60, 'Despesa', '2026-05-03', 'Seguro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Amazon Prime', 16.89, 'Despesa', '2026-05-04', 'Assinatura', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Disney+', 39.54, 'Despesa', '2026-05-06', 'Assinatura', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Spotify', 34.47, 'Despesa', '2026-05-06', 'Assinatura', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Aula particular', 136.40, 'Receita', '2026-05-09', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Spotify', 26.14, 'Despesa', '2026-05-09', 'Assinatura', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Restaurante', 96.82, 'Despesa', '2026-05-13', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Combustível', 304.82, 'Despesa', '2026-05-17', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Juros de cheque especial', 72.52, 'Despesa', '2026-05-18', 'Financeiro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Bar com amigos', 120.40, 'Despesa', '2026-05-19', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Jogo na Steam', 154.84, 'Despesa', '2026-05-21', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Salário mensal', 4452.08, 'Receita', '2026-05-26', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Reembolso', 283.99, 'Receita', '2026-05-29', 'Outras Entradas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Bônus de desempenho', 2251.99, 'Receita', '2026-06-01', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Restituição', 172.57, 'Receita', '2026-06-06', 'Outras Entradas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Venda de console de videogame', 660.81, 'Receita', '2026-06-11', 'Venda', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Presente de aniversário', 118.17, 'Despesa', '2026-06-11', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Material de escritório', 189.07, 'Despesa', '2026-06-12', 'Empresarial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Transporte por aplicativo', 20.20, 'Despesa', '2026-06-13', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Seguro residencial', 162.10, 'Despesa', '2026-06-14', 'Seguro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Mensalidade da faculdade', 1240.21, 'Despesa', '2026-06-18', 'Educacao', '2027-07-13');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Livros', 96.82, 'Despesa', '2026-06-18', 'Educacao', '2027-10-11');
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Seguro do carro', 503.15, 'Despesa', '2026-06-20', 'Seguro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Conta de celular', 60.95, 'Despesa', '2026-06-23', 'Conta Essencial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Doação', 156.68, 'Despesa', '2026-06-25', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Bônus de desempenho', 1263.24, 'Receita', '2026-06-27', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Presente em dinheiro', 217.56, 'Receita', '2026-07-03', 'Outras Entradas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Manutenção de sistema', 910.23, 'Receita', '2026-07-13', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Pet shop', 119.39, 'Despesa', '2026-07-13', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('YouTube Premium', 25.35, 'Despesa', '2026-07-14', 'Assinatura', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Condomínio', 270.02, 'Despesa', '2026-07-18', 'Conta Essencial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('13º salário', 2655.81, 'Receita', '2026-07-22', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Contador', 532.79, 'Despesa', '2026-07-26', 'Empresarial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Férias', 4350.78, 'Receita', '2026-07-27', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Farmácia', 126.66, 'Despesa', '2026-07-30', 'Saúde', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Design de logo', 326.81, 'Receita', '2026-07-30', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Academia', 142.28, 'Despesa', '2026-07-30', 'Saúde', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('13º salário', 2625.70, 'Receita', '2026-07-31', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Férias', 4038.01, 'Receita', '2026-08-12', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Livros', 133.09, 'Despesa', '2026-08-28', 'Educacao', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Restaurante', 145.78, 'Despesa', '2026-09-06', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Seguro do carro', 480.60, 'Despesa', '2026-09-08', 'Seguro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Transporte por aplicativo', 13.26, 'Despesa', '2026-09-09', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Imposto de Renda', 1019.70, 'Despesa', '2026-09-16', 'Fiscal', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Barbearia/salão', 145.17, 'Despesa', '2026-10-01', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Tarifa bancária', 16.58, 'Despesa', '2026-10-01', 'Financeiro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Show', 182.27, 'Despesa', '2026-10-01', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Seguro de vida', 111.05, 'Despesa', '2026-10-02', 'Seguro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Aluguel', 1742.65, 'Despesa', '2026-10-02', 'Conta Essencial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Certificação', 396.20, 'Despesa', '2026-10-02', 'Educacao', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Venda de roupas', 141.85, 'Receita', '2026-10-02', 'Venda', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Taxa de licenciamento', 152.39, 'Despesa', '2026-10-02', 'Fiscal', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Curso online', 258.03, 'Despesa', '2026-10-02', 'Educacao', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Bar com amigos', 153.69, 'Despesa', '2026-10-02', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Venda de roupas', 114.29, 'Receita', '2026-10-02', 'Venda', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Pet shop', 201.63, 'Despesa', '2026-10-02', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Venda de console de videogame', 697.72, 'Receita', '2026-10-02', 'Venda', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Barbearia/salão', 112.29, 'Despesa', '2026-10-03', 'Outras Saídas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Tradução de documento', 590.63, 'Receita', '2026-10-03', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Fatura do cartão de crédito', 1561.22, 'Despesa', '2026-10-03', 'Financeiro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Bar com amigos', 52.88, 'Despesa', '2026-10-03', 'Lazer', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Design de logo', 728.43, 'Receita', '2026-10-03', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Seguro residencial', 167.72, 'Despesa', '2026-10-03', 'Seguro', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Conta de água', 84.97, 'Despesa', '2026-10-03', 'Conta Essencial', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Reembolso', 227.36, 'Receita', '2026-10-03', 'Outras Entradas', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Bônus de desempenho', 596.47, 'Receita', '2026-10-03', 'Salario', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Tradução de documento', 299.22, 'Receita', '2026-10-03', 'Trabalho/Freelance', NULL);
INSERT INTO transactions (description, t_value, t_type, t_date, category, end_date) VALUES ('Projeto freelance de site', 2246.11, 'Receita', '2026-10-03', 'Trabalho/Freelance', NULL);

COMMIT;